version: 0.2

env:
  variables:
    NODE_ENV: "test"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      
  pre_build:
    commands:
      - npm install
      #- npm run lint
  build:
    commands:
      - npm run test
      - npm run build

artifacts:
  discard-paths: yes

  files:
    - "**/*"
  #name: "web-app-build"
 # base-directory: build

cache:
  paths:
    - '/root/.npm/**/*'
